# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kwil/tx/v1/price.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kwil.tx.v1 import tx_pb2 as kwil_dot_tx_dot_v1_dot_tx__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16kwil/tx/v1/price.proto\x12\x02tx\x1a\x13kwil/tx/v1/tx.proto\"*\n\x14\x45stimatePriceRequest\x12\x12\n\x02tx\x18\x01 \x01(\x0b\x32\x06.tx.Tx\"&\n\x15\x45stimatePriceResponse\x12\r\n\x05price\x18\x01 \x01(\tB\x1eZ\x1ckwil/api/protobuf/tx/v1;txpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kwil.tx.v1.price_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\034kwil/api/protobuf/tx/v1;txpb'
  _ESTIMATEPRICEREQUEST._serialized_start=51
  _ESTIMATEPRICEREQUEST._serialized_end=93
  _ESTIMATEPRICERESPONSE._serialized_start=95
  _ESTIMATEPRICERESPONSE._serialized_end=133
# @@protoc_insertion_point(module_scope)
