# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kwil/tx/v1/validator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kwil.tx.v1 import tx_pb2 as kwil_dot_tx_dot_v1_dot_tx__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1akwil/tx/v1/validator.proto\x12\x02tx\x1a\x13kwil/tx/v1/tx.proto\"*\n\tValidator\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\x12\r\n\x05power\x18\x02 \x01(\x03\"*\n\x18ValidatorApprovalRequest\x12\x0e\n\x06PubKey\x18\x01 \x01(\x0c\"K\n\x19ValidatorApprovalResponse\x12!\n\x06status\x18\x01 \x01(\x0e\x32\x11.tx.RequestStatus\x12\x0b\n\x03log\x18\x02 \x01(\t\"3\n\x14ValidatorJoinRequest\x12\x1b\n\x02tx\x18\x01 \x01(\x0b\x32\x0f.tx.Transaction\"?\n\x15ValidatorJoinResponse\x12&\n\x07receipt\x18\x01 \x01(\x0b\x32\x15.tx.TransactionStatus\"4\n\x15ValidatorLeaveRequest\x12\x1b\n\x02tx\x18\x01 \x01(\x0b\x32\x0f.tx.Transaction\"@\n\x16ValidatorLeaveResponse\x12&\n\x07receipt\x18\x01 \x01(\x0b\x32\x15.tx.TransactionStatus\"\x1a\n\x18\x43urrentValidatorsRequest\">\n\x19\x43urrentValidatorsResponse\x12!\n\nvalidators\x18\x01 \x03(\x0b\x32\r.tx.Validator\",\n\x1aValidatorJoinStatusRequest\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\"\x8e\x01\n\x1bValidatorJoinStatusResponse\x12\x30\n\x13\x61pproved_validators\x18\x01 \x03(\x0cR\x13\x61pproved_validators\x12.\n\x12pending_validators\x18\x02 \x03(\x0cR\x12pending_validators\x12\r\n\x05power\x18\x03 \x01(\x03*\"\n\rRequestStatus\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\x42\x35Z3github.com/kwilteam/kwil-db/api/protobuf/tx/v1;txpbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kwil.tx.v1.validator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z3github.com/kwilteam/kwil-db/api/protobuf/tx/v1;txpb'
  _REQUESTSTATUS._serialized_start=741
  _REQUESTSTATUS._serialized_end=775
  _VALIDATOR._serialized_start=55
  _VALIDATOR._serialized_end=97
  _VALIDATORAPPROVALREQUEST._serialized_start=99
  _VALIDATORAPPROVALREQUEST._serialized_end=141
  _VALIDATORAPPROVALRESPONSE._serialized_start=143
  _VALIDATORAPPROVALRESPONSE._serialized_end=218
  _VALIDATORJOINREQUEST._serialized_start=220
  _VALIDATORJOINREQUEST._serialized_end=271
  _VALIDATORJOINRESPONSE._serialized_start=273
  _VALIDATORJOINRESPONSE._serialized_end=336
  _VALIDATORLEAVEREQUEST._serialized_start=338
  _VALIDATORLEAVEREQUEST._serialized_end=390
  _VALIDATORLEAVERESPONSE._serialized_start=392
  _VALIDATORLEAVERESPONSE._serialized_end=456
  _CURRENTVALIDATORSREQUEST._serialized_start=458
  _CURRENTVALIDATORSREQUEST._serialized_end=484
  _CURRENTVALIDATORSRESPONSE._serialized_start=486
  _CURRENTVALIDATORSRESPONSE._serialized_end=548
  _VALIDATORJOINSTATUSREQUEST._serialized_start=550
  _VALIDATORJOINSTATUSREQUEST._serialized_end=594
  _VALIDATORJOINSTATUSRESPONSE._serialized_start=597
  _VALIDATORJOINSTATUSRESPONSE._serialized_end=739
# @@protoc_insertion_point(module_scope)
